home_dir = '/path/to/SCIGEN' # Same as PROJECT_ROOT
hydra_dir = 'path/to/HYDRA_JOBS/singlerun' # Set as HYDRA_JOBS/singlerun/
job_dir = 'yyyy-mm-dd/expname' # The directory where the model chkpt/data data stored
out_name = 'sc_kag500_000'   #'Output name of generated materials'
gnn_eval_path = './gnn_eval'
stab_pred_name_A = "stab_240409-113155"    # 'yymmdd-hhmmss' # The model name for stability prediction (A)
stab_pred_name_B = "stab_240402-111754"   # 'yymmdd-hhmmss' # The model name for stability prediction (B)
mag_pred_name = "mag_240815-085301"   # 'yymmdd-hhmmss' # The model name for magnetic prediction
seedn = 42